server:
  port: 8080
  
spring:
  application:
    name: PSP
    
  messages:
    basename: i18n/messages
    
  docker:
    compose:
      enabled: false

acquirer:
  base:
    url: http://localhost:8085/api/v1/acquirer